In [1]:
import numpy as np

In [3]:
one = np.ones((2,3),dtype=int)
one

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
two = np.array([np.arange(0,10,2) for _ in range(0,3)])
two

array([[0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [16]:
np.random.random((3,4))

array([[0.77475075, 0.3721775 , 0.52885689, 0.57353446],
       [0.55392905, 0.61877176, 0.82590606, 0.94286409],
       [0.4892865 , 0.67380597, 0.40405272, 0.41677943]])

In [17]:
np.unique(one)

array([1])

In [19]:
ar = np.random.randint(0,3,(3,4))
ar

array([[2, 2, 0, 2],
       [1, 1, 1, 0],
       [0, 2, 1, 2]])

In [20]:
np.unique(ar)

array([0, 1, 2])

In [23]:
for i in ar:
    print(np.unique(i))

[0 2]
[0 1]
[0 1 2]
