# Introduction to Scikit-Learn (sklearn)

what we're going to cover:

0. An end-to-end scikit-learn workflow
1. Getting the data ready
2. Choose the right estimater/algorithm for our problems 
3. Fit the models/algorthms and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and load  a trained model
7. Putting it all together 

## 0. And end-to-end scikit-learn workflow

In [2]:
# 1.Get the data ready
import pandas as pd
import numpy as np
heart = pd.read_csv('data/heart-disease.csv')
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [2]:
# Create X (feature matrix) 
X = heart.drop('target',axis=1)

#Create Y (labels)
Y = heart.target

In [3]:
# 2. Choose the right model and hyperparameters
from  sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [4]:
# 3.Fit the model to the training data 
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=(0.2))

In [5]:
clf.fit(X_train,Y_train);

In [6]:
# to ignore warnings 
import warnings
warnings.filterwarnings("ignore")

In [7]:
# make a prediction 
y_preds =clf.predict(heart[0:1].drop('target',axis=1));
y_preds
# len(heart[0:1].columns)

array([1], dtype=int64)

In [8]:
y_preds = clf.predict(X_test)

In [9]:
y_preds

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

In [10]:
Y_test

52     1
221    0
235    0
191    0
214    0
      ..
88     1
120    1
154    1
84     1
109    1
Name: target, Length: 61, dtype: int64

In [11]:
# 4.Evaluating the model on the training data
clf.score(X_train, Y_train)

1.0

In [12]:
clf.score(X_test, Y_test)

0.819672131147541

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(Y_test,y_preds))

              precision    recall  f1-score   support

           0       0.83      0.80      0.81        30
           1       0.81      0.84      0.83        31

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61



In [14]:
confusion_matrix(Y_test, y_preds)

array([[24,  6],
       [ 5, 26]], dtype=int64)

In [15]:
accuracy_score(Y_test, y_preds)

0.819672131147541

In [16]:
# 5.Improve the model 
# Try different amount of n_estimators
np.random.seed(42)
for i in range(1,200,10):
    print(f"Trying model with different {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, Y_train)
    # y_preds = clf.predict(X_test)
    print(f'score : {clf.score(X_test, Y_test)*100:.2f}%')

Trying model with different 1 estimators...
score : 73.77%
Trying model with different 11 estimators...
score : 80.33%
Trying model with different 21 estimators...
score : 80.33%
Trying model with different 31 estimators...
score : 85.25%
Trying model with different 41 estimators...
score : 83.61%
Trying model with different 51 estimators...
score : 81.97%
Trying model with different 61 estimators...
score : 80.33%
Trying model with different 71 estimators...
score : 80.33%
Trying model with different 81 estimators...
score : 81.97%
Trying model with different 91 estimators...
score : 83.61%
Trying model with different 101 estimators...
score : 81.97%
Trying model with different 111 estimators...
score : 81.97%
Trying model with different 121 estimators...
score : 83.61%
Trying model with different 131 estimators...
score : 85.25%
Trying model with different 141 estimators...
score : 83.61%
Trying model with different 151 estimators...
score : 83.61%
Trying model with different 161 est

In [17]:
# 6. Save the model and load it
clf = RandomForestClassifier(n_estimators=83).fit(X_train,Y_train)
import pickle 
pickle.dump(clf,open("random_forst_model_1.pkl", "wb")) # write binaries

In [18]:
loaded_model = pickle.load(open("random_forst_model_1.pkl", "rb")) # read binaries
loaded_model.score(X_test,Y_test)

0.8360655737704918

In [19]:
import sklearn
sklearn.__version__

'1.4.2'

In [20]:
sklearn.show_versions()


System:
    python: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
executable: C:\Users\Nitin\miniconda3\envs\env\python.exe
   machine: Windows-11-10.0.22631-SP0

Python dependencies:
      sklearn: 1.4.2
          pip: 24.0
   setuptools: 69.5.1
        numpy: 1.26.4
        scipy: 1.13.1
       Cython: None
       pandas: 2.2.2
   matplotlib: 3.8.4
       joblib: 1.4.2
threadpoolctl: 2.2.0

Built with OpenMP: True

threadpoolctl info:
       filepath: C:\Users\Nitin\miniconda3\envs\env\Library\bin\mkl_rt.2.dll
         prefix: mkl_rt
       user_api: blas
   internal_api: mkl
        version: 2023.1-Product
    num_threads: 6
threading_layer: intel

       filepath: C:\Users\Nitin\miniconda3\envs\env\vcomp140.dll
         prefix: vcomp
       user_api: openmp
   internal_api: openmp
        version: None
    num_threads: 12


## 1. Getting our data ready
### 1.1 Make sure it's all Numerical

In [21]:
car_sales = pd.read_csv('./data/car-sales-extended.csv')
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [22]:
len(car_sales)

1000

In [23]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [24]:
# Split into X/y
X = car_sales.drop("Price",axis = 1)
y = car_sales["Price"]

#Split into training and testing sets

x_train, x_test, y_train , y_test = train_test_split(X,y,test_size = 0.2)

In [25]:
#Build a Machine Learning Model
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()


In [26]:
# converting the nominal categorical data to numerical form
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ohe = OneHotEncoder(sparse_output=False)
transformer = ColumnTransformer([(
    'trans1', ohe,['Make','Colour'] )],remainder="passthrough")

In [27]:
x_trans_train = transformer.fit_transform(x_train
                                         )
x_trans_test = transformer.fit_transform(x_test)

In [28]:
model.fit(x_trans_train,y_train);

In [29]:
model.score(x_trans_test,y_test)

0.2742554372425341

In [30]:
x_train = pd.DataFrame(x_trans_train)
x_test = pd.DataFrame(x_trans_test)
np.random.seed(42)

In [31]:
model.fit(x_train,y_train)

RandomForestRegressor()

In [32]:
model.score(x_test,y_test)

0.27464013550660915

### 1.2 what if there were missing values
1. fill them with some value(also know as imputation )
2. Remove the samples with missing data altogether

In [33]:
car_sales_missing = pd.read_csv('./data/car-sales-missing-data.csv')
car_sales_missing.isna().sum()

Make        1
Colour      1
Odometer    4
Doors       1
Price       2
dtype: int64

In [34]:
# create X and y
X = car_sales_missing.drop(columns='Price')
y = car_sales_missing.Price

In [35]:
x_trans = transformer.fit_transform(X)
x_trans[:3]
sklearn.__version__ # updated version of sklearn handles nan values 

'1.4.2'

### option 1. Fill missing values with pandas

In [36]:
car_sales_missing.dtypes

Make         object
Colour       object
Odometer    float64
Doors       float64
Price        object
dtype: object

In [37]:
def convert_price(price):
    # Remove the dollar sign and comma, then convert to integer
    price = str(price)
    pri = price.replace('$', '').replace(',' , '')
    pri = float(pri)
    return pri

# Apply the function to the 'price' column
car_sales_missing['Price'] = car_sales_missing['Price'].apply(convert_price)

In [38]:
car_sales_missing.Make.fillna("missing", inplace = True)
car_sales_missing.Colour.fillna("missing",inplace=True)
car_sales_missing['Odometer'].fillna(car_sales_missing['Odometer'].mean(),inplace=True)
car_sales_missing.Doors.fillna(4,inplace=True)
car_sales_missing.Price.fillna(car_sales_missing.Price.mean(),inplace=True)
car_sales_missing.isna().sum()

Make        0
Colour      0
Odometer    0
Doors       0
Price       0
dtype: int64

In [39]:
X = car_sales_missing.drop(columns='Price')
y = car_sales_missing.Price
X_trans = transformer.fit_transform(X)

In [40]:
x_train, x_test,  y_train, y_test = train_test_split(X_trans,y,test_size= 0.2)

In [41]:
model.fit(x_train,y_train);

In [42]:
model.score(x_test, y_test)

0.04689812244897962

### option 2. Remove rows

In [43]:
car_sales_missing = pd.read_csv('./data/car-sales-missing-data.csv')
car_sales_missing.dropna(inplace= True)

In [44]:
car_sales_missing.isna().sum()

Make        0
Colour      0
Odometer    0
Doors       0
Price       0
dtype: int64

In [45]:
def convert_price(price):
    # Remove the dollar sign and comma, then convert to integer
    price = str(price)
    pri = price.replace('$', '').replace(',' , '')
    pri = float(pri)
    return pri

# Apply the function to the 'price' column
car_sales_missing['Price'] = car_sales_missing['Price'].apply(convert_price)
X = car_sales_missing.drop(columns='Price')
y = car_sales_missing.Price
X_trans = transformer.fit_transform(X)

In [46]:
x_train, x_test,  y_train, y_test = train_test_split(X_trans,y,test_size= 0.2)

In [47]:
model.fit(x_train,y_train)

RandomForestRegressor()

In [48]:
model.score(x_test, y_test)

nan

### 1.3. Inputing

In [49]:
# filling missing values with sklearn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# fill the categorical values with 'missing' and numerical values with mean
cat_imp = SimpleImputer(strategy= 'constant',fill_value='missing')
door_imp = SimpleImputer(strategy='constant', fill_value = 4)
num_imp = SimpleImputer(strategy = 'mean')

# define columns 
cat_features  = [ 'Make','Colour']
door_features = ['Doors']
num_features = ['Odometer']

# transformer
transformer = ColumnTransformer([
    ('cat', cat_imp, cat_features),
    ('door', door_imp,door_features),
    ('num', num_imp, num_features)
    ], remainder = "passthrough")

In [50]:
car_sales_missing = pd.read_csv('./data/car-sales-missing-data.csv')
X = car_sales_missing.drop(columns = "Price")
y = car_sales_missing.Price
X

Make Colour  Odometer  Doors
0  Toyota  White  150043.0    4.0
1   Honda    Red   87899.0    4.0
2  Toyota   Blue       NaN    3.0
3     BMW  Black   11179.0    5.0
4  Nissan  White  213095.0    4.0
5  Toyota  Green       NaN    4.0
6   Honda    NaN       NaN    4.0
7   Honda   Blue       NaN    4.0
8  Toyota  White   60000.0    NaN
9     NaN  White   31600.0    4.0

In [51]:
x = transformer.fit_transform(X)

In [52]:
X = pd.DataFrame(x)
price_imp  = SimpleImputer(stategy="constant", fill_value=0)
trans = ColumnTransformer([
    ('ytrans', cat_imp, 'Price')],remainder="passthrough")
y = pd.DataFrame(columns=['Price'],data = y)
# y = trans.fit_transform(y)
y

TypeError: SimpleImputer.__init__() got an unexpected keyword argument 'stategy'

## 2. Choosing the right estimator/algorithm for your problem
some things to note:
* sklearn referes to machine learning models, algorithms as estimators
* classification problem - predicting a category (heart disease or not)
      * sometimes you'll see 'clf' (short for classifier) used as  a classification estimator
* Regression problem - predicting a number(selling price ) 

### 2.1 Picking a machine learning model for a regression problem
let's use California  housing data sets

In [ ]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

In [ ]:
housing

In [ ]:
housing_df = pd.DataFrame(housing['data'], columns = housing.feature_names)
housing_df

In [ ]:
housing_df['target']  = housing['target']
housing_df.head()

In [ ]:
housing_df.isna().sum()

In [ ]:
# import algorithm

# set up random seed
np.random.seed(42)

#create the data
X = housing_df.drop(columns = 'target')
y = housing_df.target

# split the data 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

#instantiate and fit the model 
from sklearn.linear_model import Ridge
model = Ridge()
model.fit(x_train, y_train)

In [ ]:
model.score(x_test, y_test)

In [ ]:
from sklearn import linear_model

In [ ]:
model = linear_model.LinearRegression()
model.fit(x_train, y_train)

In [ ]:
model.score(x_test, y_test)

In [ ]:
reg = linear_model.LassoLars(alpha = .1)
reg.fit(x_train, y_train)

In [ ]:
reg.score(x_test, y_test)

In [ ]:
# import the RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=120)
model.fit(x_train, y_train)

In [ ]:
model.score(x_test, y_test)

### 2.2 Picking a ml algorithm for classification

In [249]:
np.random.seed(42)
heart = pd.read_csv('./data/heart-disease.csv')
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [55]:
len(heart)

303

In [60]:
from sklearn.model_selection import train_test_split
from sklearn import svm
X = heart.drop(columns= "target")
y = heart.target
clf = svm.SVC()
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
clf.fit(x_train,y_train)

SVC()

In [61]:
clf.score(x_test,y_test)

0.6065573770491803

In [118]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=20)
neigh.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=20)

In [119]:
neigh.score(x_test,y_test)

0.6885245901639344

In [162]:
from sklearn.ensemble import HistGradientBoostingClassifier
clf = HistGradientBoostingClassifier(max_iter=10).fit(x_train,y_train)

In [163]:
clf.score(x_test,y_test)

0.8360655737704918

In [224]:
from sklearn.svm import LinearSVC
clf = LinearSVC(max_iter= 1000,random_state=12, tol=1e-5)
clf.fit(x_train,y_train)

LinearSVC(random_state=12, tol=1e-05)

In [225]:
clf.score(x_test, y_test)

0.8360655737704918

In [270]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=80)
clf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=80)

In [271]:
clf.score(x_test,y_test)

0.819672131147541

Tidbit:

        1. if u have structured data use ensemble models
        2. if u have unstructured data use deep learning or transfer learning

## 3. fit the model on our data and use it to make predictions


### 3.1 fitting the model to the data

Different names for:
* `X` = features, features variables, data
* `y` = lablels, targets, target variables 

In [275]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

heart = pd.read_csv('./data/heart-disease.csv')
X = heart.drop(columns = 'target')
y = heart.target
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
clf = RandomForestClassifier(n_estimators=80)

# fit the model(training the model on our data)
clf.fit(x_train,y_train)

# Evaluate the model(use the patterns the model has learnt )
clf.score(x_test, y_test)

0.8032786885245902

### 3.2 Make predictions using our ml model
2 ways to make predictions
1. `predict()`
2. `predict_proba()`

In [278]:
# use a trained model to make predictions 
y_preds = clf.predict(x_test)
y_preds

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [279]:
np.array(y_test)

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0], dtype=int64)

In [280]:
np.mean(y_test == y_preds)

0.8032786885245902

In [281]:
clf.score(x_test, y_test)

0.8032786885245902

In [282]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8032786885245902

 Make predictions with `predict_proba()`

In [289]:
# predict_proba() returns probabilities of a classification label
clf.predict_proba(x_test[:6])

array([[0.7   , 0.3   ],
       [0.2375, 0.7625],
       [0.0375, 0.9625],
       [0.0375, 0.9625],
       [0.4125, 0.5875],
       [0.55  , 0.45  ]])

In [290]:
clf.predict(x_test[:6])

array([0, 1, 1, 1, 1, 0], dtype=int64)

In [291]:
y_test[:6]

138    1
27     1
49     1
154    1
141    1
273    0
Name: target, dtype: int64

In [4]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing_df = pd.DataFrame(housing.data, columns = housing.feature_names)
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [8]:
housing_target= pd.DataFrame(housing.target, columns = ['MedHouseVal'])
housing_target.head()

MedHouseVal
0        4.526
1        3.585
2        3.521
3        3.413
4        3.422

In [15]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
X  = housing_df
y = housing_target
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size= 0.2)
regr = RandomForestRegressor(n_estimators = 100)
regr.fit(x_train, y_train)

C:\Users\Nitin\miniconda3\envs\env\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor()

In [17]:
regr.score(x_test, y_test)

0.8140692251631703

In [59]:
y_pred = regr.predict(x_test)
y_pred

array([1.66844  , 3.6881914, 2.5090102, ..., 4.6709148, 4.2646258,
       1.40635  ])

In [61]:
y_test = np.array(y_test)

In [62]:
# compare the predictions with the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_pred, y_test)

0.3185135485949614