# Introduction to Scikit-Learn (sklearn)

what we're going to cover:

0. An end-to-end scikit-learn workflow
1. Getting the data ready
2. Choose the right estimater/algorithm for our problems 
3. Fit the models/algorthms and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and load  a trained model
7. Putting it all together 

## 0. And end-to-end scikit-learn workflow

In [62]:
# 1.Get the data ready
import pandas as pd
import numpy as np
heart = pd.read_csv('data/heart-disease.csv')
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [63]:
# Create X (feature matrix) 
X = heart.drop('target',axis=1)

#Create Y (labels)
Y = heart.target

In [82]:
# 2. Choose the right model and hyperparameters
from  sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [83]:
# 3.Fit the model to the training data 
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=(0.2))

In [84]:
clf.fit(X_train,Y_train);

In [85]:
# to ignore warnings 
import warnings
warnings.filterwarnings("default")

In [89]:
# make a prediction 
y_preds =clf.predict(heart[0:1].drop('target',axis=1));
y_preds
# len(heart[0:1].columns)

array([1])

In [69]:
y_preds = clf.predict(X_test)

In [70]:
y_preds

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1])

In [71]:
Y_test

0      1
131    1
264    0
208    0
254    0
      ..
126    1
32     1
265    0
275    0
26     1
Name: target, Length: 61, dtype: int64

In [72]:
# 4.Evaluating the model on the training data
clf.score(X_train, Y_train)

1.0

In [73]:
clf.score(X_test, Y_test)

0.8852459016393442

In [74]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(Y_test,y_preds))

              precision    recall  f1-score   support

           0       0.86      0.89      0.88        28
           1       0.91      0.88      0.89        33

    accuracy                           0.89        61
   macro avg       0.88      0.89      0.88        61
weighted avg       0.89      0.89      0.89        61



In [75]:
confusion_matrix(Y_test, y_preds)

array([[25,  3],
       [ 4, 29]])

In [76]:
accuracy_score(Y_test, y_preds)

0.8852459016393442

In [77]:
# 5.Improve the model 
# Try different amount of n_estimators
np.random.seed(42)
for i in range(1,200,10):
    print(f"Trying model with different {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, Y_train)
    # y_preds = clf.predict(X_test)
    print(f'score : {clf.score(X_test, Y_test)*100:.2f}%')

Trying model with different 1 estimators...
score : 75.41%
Trying model with different 11 estimators...
score : 80.33%
Trying model with different 21 estimators...
score : 85.25%
Trying model with different 31 estimators...
score : 86.89%
Trying model with different 41 estimators...
score : 81.97%
Trying model with different 51 estimators...
score : 83.61%
Trying model with different 61 estimators...
score : 83.61%
Trying model with different 71 estimators...
score : 86.89%
Trying model with different 81 estimators...
score : 86.89%
Trying model with different 91 estimators...
score : 85.25%
Trying model with different 101 estimators...
score : 85.25%
Trying model with different 111 estimators...
score : 85.25%
Trying model with different 121 estimators...
score : 88.52%
Trying model with different 131 estimators...
score : 86.89%
Trying model with different 141 estimators...
score : 83.61%
Trying model with different 151 estimators...
score : 86.89%
Trying model with different 161 est

In [90]:
# 6. Save the model and load it
clf = RandomForestClassifier(n_estimators=11).fit(X_train,Y_train)
import pickle 
pickle.dump(clf,open("random_forst_model_1.pkl", "wb")) # write binaries

/tmp/ipykernel_6438/783538516.py:4: ResourceWarning: unclosed file <_io.BufferedWriter name='random_forst_model_1.pkl'>
  pickle.dump(clf,open("random_forst_model_1.pkl", "wb")) # write binaries


In [91]:
loaded_model = pickle.load(open("random_forst_model_1.pkl", "rb")) # read binaries
loaded_model.score(X_test,Y_test)

/tmp/ipykernel_6438/925387663.py:1: ResourceWarning: unclosed file <_io.BufferedReader name='random_forst_model_1.pkl'>
  loaded_model = pickle.load(open("random_forst_model_1.pkl", "rb")) # read binaries


0.8688524590163934

In [92]:
import sklearn
sklearn.__version__

'1.4.2'

In [93]:
sklearn.show_versions()


System:
    python: 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:46:43) [GCC 11.2.0]
executable: /home/vicki/ML/udemy/env/bin/python
   machine: Linux-6.6.9-amd64-x86_64-with-glibc2.37

Python dependencies:
      sklearn: 1.4.2
          pip: 24.0
   setuptools: 69.5.1
        numpy: 1.26.4
        scipy: 1.13.0
       Cython: None
       pandas: 2.2.1
   matplotlib: 3.8.4
       joblib: 1.4.0
threadpoolctl: 2.2.0

Built with OpenMP: True

threadpoolctl info:
       filepath: /home/vicki/ML/udemy/env/lib/libmkl_rt.so.2
         prefix: libmkl_rt
       user_api: blas
   internal_api: mkl
        version: 2023.1-Product
    num_threads: 6
threading_layer: intel

       filepath: /home/vicki/ML/udemy/env/lib/libiomp5.so
         prefix: libiomp
       user_api: openmp
   internal_api: openmp
        version: None
    num_threads: 12

       filepath: /home/vicki/ML/udemy/env/lib/libgomp.so.1.0.0
         prefix: libgomp
       user_api: openmp
   internal_api: openmp
   