# Introduction to Scikit-Learn (sklearn)

what we're going to cover:

0. An end-to-end scikit-learn workflow
1. Getting the data ready
2. Choose the right estimater/algorithm for our problems 
3. Fit the models/algorthms and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and load  a trained model
7. Putting it all together 

## 0. And end-to-end scikit-learn workflow

In [1]:
# 1.Get the data ready
import pandas as pd
import numpy as np
heart = pd.read_csv('data/heart-disease.csv')
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [2]:
# Create X (feature matrix) 
X = heart.drop('target',axis=1)

#Create Y (labels)
Y = heart.target

In [36]:
# 2. Choose the right model and hyperparameters
from  sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [4]:
# 3.Fit the model to the training data 
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=(0.2))

In [5]:
clf.fit(X_train,Y_train);

In [22]:
# to ignore warnings 
import warnings
warnings.filterwarnings("ignore")

In [23]:
# make a prediction 
y_preds =clf.predict(heart[0:1].drop('target',axis=1));
y_preds
# len(heart[0:1].columns)

array([1], dtype=int64)

In [24]:
y_preds = clf.predict(X_test)

In [25]:
y_preds

array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1], dtype=int64)

In [26]:
Y_test

52     1
263    0
240    0
249    0
53     1
      ..
174    0
116    1
40     1
8      1
91     1
Name: target, Length: 61, dtype: int64

In [27]:
# 4.Evaluating the model on the training data
clf.score(X_train, Y_train)

0.9958677685950413

In [28]:
clf.score(X_test, Y_test)

0.7868852459016393

In [29]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(Y_test,y_preds))

              precision    recall  f1-score   support

           0       0.77      0.80      0.79        30
           1       0.80      0.77      0.79        31

    accuracy                           0.79        61
   macro avg       0.79      0.79      0.79        61
weighted avg       0.79      0.79      0.79        61



In [30]:
confusion_matrix(Y_test, y_preds)

array([[24,  6],
       [ 7, 24]], dtype=int64)

In [31]:
accuracy_score(Y_test, y_preds)

0.7868852459016393

In [37]:
# 5.Improve the model 
# Try different amount of n_estimators
np.random.seed(42)
for i in range(1,200,10):
    print(f"Trying model with different {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, Y_train)
    # y_preds = clf.predict(X_test)
    print(f'score : {clf.score(X_test, Y_test)*100:.2f}%')

Trying model with different 1 estimators...
score : 72.13%
Trying model with different 11 estimators...
score : 77.05%
Trying model with different 21 estimators...
score : 75.41%
Trying model with different 31 estimators...
score : 81.97%
Trying model with different 41 estimators...
score : 78.69%
Trying model with different 51 estimators...
score : 80.33%
Trying model with different 61 estimators...
score : 83.61%
Trying model with different 71 estimators...
score : 80.33%
Trying model with different 81 estimators...
score : 81.97%
Trying model with different 91 estimators...
score : 81.97%
Trying model with different 101 estimators...
score : 80.33%
Trying model with different 111 estimators...
score : 83.61%
Trying model with different 121 estimators...
score : 81.97%
Trying model with different 131 estimators...
score : 80.33%
Trying model with different 141 estimators...
score : 81.97%
Trying model with different 151 estimators...
score : 78.69%
Trying model with different 161 est

In [33]:
# 6. Save the model and load it
clf = RandomForestClassifier(n_estimators=83).fit(X_train,Y_train)
import pickle 
pickle.dump(clf,open("random_forst_model_1.pkl", "wb")) # write binaries

In [34]:
loaded_model = pickle.load(open("random_forst_model_1.pkl", "rb")) # read binaries
loaded_model.score(X_test,Y_test)

0.7868852459016393

In [19]:
import sklearn
sklearn.__version__

'1.4.2'

In [20]:
sklearn.show_versions()


System:
    python: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
executable: C:\Users\Nitin\miniconda3\envs\env\python.exe
   machine: Windows-11-10.0.22631-SP0

Python dependencies:
      sklearn: 1.4.2
          pip: 24.0
   setuptools: 69.5.1
        numpy: 1.26.4
        scipy: 1.13.1
       Cython: None
       pandas: 2.2.2
   matplotlib: 3.8.4
       joblib: 1.4.2
threadpoolctl: 2.2.0

Built with OpenMP: True

threadpoolctl info:
       filepath: C:\Users\Nitin\miniconda3\envs\env\Library\bin\mkl_rt.2.dll
         prefix: mkl_rt
       user_api: blas
   internal_api: mkl
        version: 2023.1-Product
    num_threads: 6
threading_layer: intel

       filepath: C:\Users\Nitin\miniconda3\envs\env\vcomp140.dll
         prefix: vcomp
       user_api: openmp
   internal_api: openmp
        version: None
    num_threads: 12


## 1.1 Make sure it's all Numerical

In [44]:
car_sales = pd.read_csv('./data/car-sales-extended.csv')
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [43]:
len(car_sales)

1000

In [45]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [48]:
# Split into X/y
X = car_sales.drop("Price",axis = 1)
y = car_sales["Price"]

#Split into training and testing sets

x_train, x_test, y_train , y_test = train_test_split(X,y,test_size = 0.2)

In [51]:
#Build a Machine Learning Model
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train)
model.score(x_test,y_test)

ValueError: could not convert string to float: 'Honda'