In [1]:
# Numpy turns your data into a series of numbers 
# ml algo finds patterns in those numbers
#data analysis
# fast
# behind the scenes optimizations in c
# vectorization via broadcasting (avoiding loops)
# backbone of other python scientific packages


In [2]:
import numpy as np

# 1.Datatypes and Attributes

In [3]:
# numpy main data type is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[10,11,12],[13,14,15],[16,17,18]]])


In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.dtype

dtype('int32')

In [12]:
a2.dtype

dtype('float64')

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# Dataframe from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.0

In [17]:
 a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

# 2.Creating arrays

In [18]:
sample = np.array([1,2,3])
sample

array([1, 2, 3])

In [19]:
#shift + tab tells documentation of numpy 
# size parameter passing should be done like size=(m,n) / (m,n)
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0,10,size=(3,5))
random_array                                 

array([[0, 7, 0, 2, 2],
       [2, 8, 1, 9, 4],
       [8, 6, 8, 9, 8]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.43693671, 0.04967487, 0.03666049],
       [0.49225719, 0.81160425, 0.89694002],
       [0.24742777, 0.62892043, 0.17736818],
       [0.88030202, 0.7296175 , 0.8504574 ],
       [0.48848066, 0.22025468, 0.81549534]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5,3)
random_array_3 

array([[0.76352352, 0.16949296, 0.90230428],
       [0.82294401, 0.02791142, 0.38134652],
       [0.05138968, 0.1026973 , 0.62403466],
       [0.95388045, 0.31056692, 0.82279857],
       [0.02548466, 0.35870753, 0.68286641]])

In [30]:
# Pseudo random numbers
# np.random.seed(seed=0)
# setting random seed to some value does not allow our random numbers to change so that someone 
# else using our notebook can generate the exact random numbers like us 
# the random numbers generated depends on the seed value 
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[1, 4, 8],
       [5, 5, 2],
       [0, 8, 5],
       [7, 9, 6],
       [1, 2, 6]])

In [31]:
random_array_4.shape

(5, 3)

# 3.Viewing Arrays and Matrices

In [32]:
# to find unique elements in ndarray
np.unique(random_array_4)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [33]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6. ]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [34]:
a1[0]

1

In [35]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [36]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [37]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[0, 6, 1, 6, 1],
         [3, 3, 0, 1, 9],
         [5, 2, 2, 9, 1],
         [6, 5, 5, 8, 0]],

        [[9, 1, 3, 5, 3],
         [6, 5, 6, 6, 0],
         [2, 4, 8, 7, 0],
         [6, 3, 0, 6, 4]],

        [[8, 3, 8, 5, 5],
         [1, 2, 9, 9, 9],
         [7, 3, 7, 3, 3],
         [4, 0, 5, 7, 6]]],


       [[[1, 8, 6, 7, 6],
         [1, 4, 1, 8, 7],
         [0, 9, 5, 5, 0],
         [2, 7, 8, 8, 4]],

        [[9, 9, 7, 9, 7],
         [2, 6, 4, 6, 8],
         [9, 1, 3, 4, 4],
         [6, 7, 2, 4, 7]],

        [[9, 0, 5, 5, 1],
         [2, 9, 2, 8, 6],
         [1, 7, 1, 1, 6],
         [2, 6, 0, 0, 3]]]])

In [38]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [39]:
a4[1][1][0]

array([9, 9, 7, 9, 7])

In [40]:
# get first 3 numbers of the inner most arrays
a4[:,:,:,:3]

array([[[[0, 6, 1],
         [3, 3, 0],
         [5, 2, 2],
         [6, 5, 5]],

        [[9, 1, 3],
         [6, 5, 6],
         [2, 4, 8],
         [6, 3, 0]],

        [[8, 3, 8],
         [1, 2, 9],
         [7, 3, 7],
         [4, 0, 5]]],


       [[[1, 8, 6],
         [1, 4, 1],
         [0, 9, 5],
         [2, 7, 8]],

        [[9, 9, 7],
         [2, 6, 4],
         [9, 1, 3],
         [6, 7, 2]],

        [[9, 0, 5],
         [2, 9, 2],
         [1, 7, 1],
         [2, 6, 0]]]])

# 4.Manipulating & Comparing Arrays

### Arithmetic

In [41]:
ones=np.ones(3)
a1,ones

(array([1, 2, 3]), array([1., 1., 1.]))

In [42]:
a1+ones

array([2., 3., 4.])

In [43]:
 a1-ones

array([0., 1., 2.])

In [44]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [45]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
a2+a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
aa2 = np.random.randint(0,3,(3,3,2,3))
aa2,a2

In [ ]:
aa2+a2

In [ ]:
np.add(a1,a2)

### Aggregation
Aggregation = performing same operations on a number of things

In [ ]:
a1.sum(), sum(a1)

use python's methods (`sum()`) on python datatypes  and use Numpy's 
methods on Numpy arrays (`np.sum()`)

In [ ]:
# creating a massive array 
mass_ar = np.random.random(100000)
mass_ar.size

In [ ]:
mass_ar[:10]

In [ ]:
%timeit  sum(mass_ar) # Python's sum()
%timeit np.sum(mass_ar) # Numpy's np.sum()

In [ ]:
a2

In [ ]:
np.mean(a2), np.max(a2), np.min(a2), np.std(a2), np.var(a2)

In [ ]:
#demo of variance and standard deviation
high_var = np.array([1,100,200,3000,4000,5000])
low_var = np.array([2,4,5,6,7,9])

In [ ]:
high_var.var(),low_var.var()

In [ ]:
high_var.std(), low_var.std()

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt 
plt.hist(high_var)
plt.show()

In [ ]:
plt.hist(low_var)
plt.show()

### Reshaping and Transposing 

In [ ]:
a2.shape, a3.shape

#### one of the rules of broadcasting :
numpy compares their shape starting with the trailing dimsons and works it way forward.
two dimsons are compatible if  :

1.they are equal

2.one of them is 1

In [ ]:
a2.reshape(2,3,1)

In [ ]:
a2.reshape(2,3,1)*a3

In [ ]:
a3.reshape(3,2,3)*a2

In [ ]:
a2, a2.shape, a3.shape

In [ ]:
# Transpose
a2.T, a2.T.shape, a3.T.shape

## Dot Product

In [ ]:
np.random.seed(0)
mat2 = np.random.randint(10,size=(5,3))
mat1 = np.random.randint(10,size=(5,3))

In [ ]:
mat1, mat2

In [ ]:
# key wise multiplication(Hadamard product)
mat1*mat2

In [ ]:
# Dot product 
np.dot(mat1,mat2.reshape(3,5))

In [ ]:
np.dot(mat1, mat2.T)

In [ ]:
t1 = np.random.randint(0,10,(100,100))
t2 = np.random.randint(0,10,(100,100))

In [ ]:
%timeit t1*t2 
%timeit np.dot(t1,t2)

## Dot product ex (nut butter sales)

In [48]:
np.random.seed(0)
# Number of jars sold
sales_am = np.random.randint(20,size=(5,3))
sales_am

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [50]:
# Create weekly_sales Dataframe
week_sales = pd.DataFrame(sales_am, index=['Mon','Tue','Wed','Thur','Fri'], columns=['Almond','Peanut','Cashew'])
week_sales

Almond  Peanut  Cashew
Mon       12      15       0
Tue        3       3       7
Wed        9      19      18
Thur       4       6      12
Fri        1       6       7

In [62]:
# Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [59]:
# create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),index=['prices'],columns=['Almond','Peanut','Cashew'])
butter_prices

Almond  Peanut  Cashew
prices      10       8      12

In [60]:
prices.shape, butter_prices.shape

((3,), (1, 3))

In [76]:
total_sales = np.dot(prices,sales_am.T)
total_sales

array([240, 138, 458, 232, 142])

In [84]:
week_sales['Total ($)']=total_sales.reshape(5,1)
# week_sales.drop(['Total'],axis=1,inplace=True)
week_sales

Almond  Peanut  Cashew  Total ($)
Mon       12      15       0        240
Tue        3       3       7        138
Wed        9      19      18        458
Thur       4       6      12        232
Fri        1       6       7        142

In [75]:
butter_prices

Almond  Peanut  Cashew
prices      10       8      12

### Comparison Operators

In [86]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6. ]]))

In [89]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [90]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

### Sorting Arrays

In [93]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [94]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [95]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [100]:
# sorting indices in place of element values returns their sorted indices / positions
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

In [101]:
a1

array([1, 2, 3])

In [102]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [105]:
np.argmax(random_array), np.argmin(random_array)

(4, 9)

In [106]:
np.argmax(a1), np.argmin(a1)

(2, 0)

In [107]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [108]:
np.argmax(random_array,axis=0) # along columns


array([1, 1, 1, 0, 0], dtype=int64)

In [110]:
np.argmax(random_array,axis=1) # along rows

array([4, 1, 1], dtype=int64)

## Practical Example - Numpy in action!!

<img src="images/panda.png"/>

In [118]:
# Turn an image into  a Numpy array
from matplotlib.image import imread
panda = imread('images/panda.png')
type(panda)

numpy.ndarray

In [119]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [120]:
panda[:2]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

<img src='images/car-photo.png' />

In [123]:
car = imread('images/car-photo.png')
car.size, car.shape, car.ndim

(991300, (431, 575, 4), 3)

<img src="images/dog-photo.png" />

In [124]:
dog = imread('images/dog-photo.png')
dog.size, dog.shape, dog.ndim

(993600, (432, 575, 4), 3)